remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Interactive SVG Schematics
description: Architect is a theme for GitHub Pages.
show_downloads: false
pages:
  - name: Page 1
    path: /page1.html
  - name: Page 2
    path: /page2.html
  - name: Page 3
    path: /page3.html